### PR TITLE
Implement trap instructions

### PR DESCRIPTION
**Pull request by lambertjamesd**
The PR implements trap instructions. I have not tested each instruction but I have verified that teq works.
I can do more testing but I wanted to get this open in case there is major feedback before I tested everything.
Fixes this issue
https://github.com/n64dev/cen64/issues/126

### CODE REVIEW

**Comment by clbr** [comment]
I think the INFO()s are wrong, the ones that take a register should include the NEED for those regs in there.

**Comment by tj90241** [comment]
yep, you want `INFO2(NEEDRS, NEEDRT)` for most/all of those.

There's also some compiler attributes that don't look correctly leveraged:
```
uint32_t unused(iw), uint64_t rs, uint64_t rt) {
...
  bool cmp = rs == (uint64_t)imm;
```
`rt` is `unused`, `imm` is used.

Otherwise, looks like a correct implementation, though.  Great job!

**Comment by lambertjamesd** [comment]
I addressed both those issues. I also wrote a test program that verifies all the trap instructions. The test program passes on real hardware and on this branch of cen64

Here is the list of test cases I am running though
```

    DO_TEST(errMessage, TEQ, 1, 0, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TEQ, 10, 12, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TEQ, 1, 1, SHOULD_TRAP);
    DO_TEST(errMessage, TEQ, -10, -10, SHOULD_TRAP);

    DO_TEST(errMessage, TEQI, 1, 1, SHOULD_TRAP);
    DO_TEST(errMessage, TEQI, 0, 1, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TEQI, -1, -1, SHOULD_TRAP);
    DO_TEST(errMessage, TEQI, 0xffff, -1, SHOULD_NOT_TRAP);

    DO_TEST(errMessage, TGE, 10, 1, SHOULD_TRAP);
    DO_TEST(errMessage, TGE, 10, 10, SHOULD_TRAP);
    DO_TEST(errMessage, TGE, 10, 20, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TGE, 10, -10, SHOULD_TRAP);
    DO_TEST(errMessage, TGE, 0x10000, 0x20000, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TGE, 0x40000, 0x20000, SHOULD_TRAP);

    DO_TEST(errMessage, TGEI, 10, 1, SHOULD_TRAP);
    DO_TEST(errMessage, TGEI, 10, 10, SHOULD_TRAP);
    DO_TEST(errMessage, TGEI, 10, 20, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TGEI, 10, -10, SHOULD_TRAP);

    DO_TEST(errMessage, TGEIU, 10, 1, SHOULD_TRAP);
    DO_TEST(errMessage, TGEIU, 10, 10, SHOULD_TRAP);
    DO_TEST(errMessage, TGEIU, 10, 20, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TGEIU, 10, -10, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TGEIU, -20, -10, SHOULD_NOT_TRAP);

    DO_TEST(errMessage, TGEU, 10, 1, SHOULD_TRAP);
    DO_TEST(errMessage, TGEU, 10, 10, SHOULD_TRAP);
    DO_TEST(errMessage, TGEU, 10, 20, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TGEU, 10, -10, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TGEU, -20, -10, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TGE, 0x10000, 0x20000, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TGE, 0x40000, 0x20000, SHOULD_TRAP);

    DO_TEST(errMessage, TLT, 10, 1, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLT, 10, 10, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLT, 10, 20, SHOULD_TRAP);
    DO_TEST(errMessage, TLT, 10, -10, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLT, -20, -10, SHOULD_TRAP);

    DO_TEST(errMessage, TLTI, 10, 1, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLTI, 10, 10, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLTI, 10, 20, SHOULD_TRAP);
    DO_TEST(errMessage, TLTI, 10, -10, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLTI, -20, -10, SHOULD_TRAP);

    DO_TEST(errMessage, TLTIU, 10, 1, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLTIU, 10, 10, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLTIU, 10, 20, SHOULD_TRAP);
    DO_TEST(errMessage, TLTIU, 10, -10, SHOULD_TRAP);
    DO_TEST(errMessage, TLTIU, 0x10000, -10, SHOULD_TRAP);
    DO_TEST(errMessage, TLTIU, -20, -10, SHOULD_TRAP);

    DO_TEST(errMessage, TLTU, 10, 1, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLTU, 10, 10, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TLTU, 10, 20, SHOULD_TRAP);
    DO_TEST(errMessage, TLTU, 10, -10, SHOULD_TRAP);
    DO_TEST(errMessage, TLTU, 0x10000, -10, SHOULD_TRAP);
    DO_TEST(errMessage, TLTU, -20, -10, SHOULD_TRAP);

    DO_TEST(errMessage, TNE, 1, 0, SHOULD_TRAP);
    DO_TEST(errMessage, TNE, 10, 12, SHOULD_TRAP);
    DO_TEST(errMessage, TNE, 1, 1, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TNE, -10, -10, SHOULD_NOT_TRAP);

    DO_TEST(errMessage, TNEI, 1, 1, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TNEI, 0, 1, SHOULD_TRAP);
    DO_TEST(errMessage, TNEI, -1, -1, SHOULD_NOT_TRAP);
    DO_TEST(errMessage, TNEI, 0xffff, -1, SHOULD_TRAP);
```

**Review by tj90241 — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
